# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
workflows:
  version: 2
  test:
    jobs:
      - python-test
      - js-test
      # - go-test

jobs:
  python-test:
    docker:
      - image: circleci/python:3.7.0
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: "prepare python env and tests"
          command: python3 -mvenv venv && . venv/bin/activate && pip install -r requirements.txt && python transaction_creator.py && python transaction_reader.py
          working_directory: python

  js-test:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.14.0
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: "prepare js package and tests"
          command: yarn install && yarn write && yarn read
          working_directory: js

#  go-test:
#    docker:
#      # specify the version you desire here
#      - image: circleci/golang:1.13.0
#    working_directory: ~/repo
#    steps:
#      - checkout
#
#      - run:
#          name: "prepare go and tests"
#          command: make all && ./transaction_creator && ./transaction_reader
#          working_directory: golang
